### ISSUE TITLE
Note in PDF di logica non è LaTeX

### ISSUE THREAD

**Issue by dddema** [MagiHotline/UniversityNotes#1]
Volevo far notare che le note in PDF di logica non sono fatte in LaTeX, sembrano bensì create usando il programma pages per **MacOS**. 

### Proofs
<img width="799" alt="image" src="https://github.com/MagiHotline/UniversityNotes/assets/31252900/8432d12c-00f7-4adc-b5bc-c60229e7ab46">

<img width="700" alt="image" src="https://github.com/MagiHotline/UniversityNotes/assets/31252900/cec07173-da18-46c0-aa92-a4994ebe492c">

Spero tu possa darmi spiegazioni, 
DDM

**Comment by MagiHotline** [comment]
# Carissimo dddema,

Ti scrivo per informarti che gli appunti di Logica li avevo fatti senza l'utilizzo di LaTeX, convinto che non esistessero packages adeguati. Non rimedierò perché non ho voglia. Ciao.

**Comment by dddema** [comment]
# OK, GRAZIE,
## DANIELE DE MARCO
